name: 02 - Eventos
on: push
jobs:
    echo: 
        runs-on: ubuntu-latest
        steps:
          - name: ShowTrigger
            run: | 
                echo "Evento que ha disparado el workflow: ${{ github.event_name }}"