name: 07 - Filters and Activity Types
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize]
        branches:
            - develop
    workflow_dispatch: 
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: |
                echo "Workflow triggered by filters or activity types"